from pygame.color import THECOLORS
import pygame

# SHAPES
WIDTH = 800
HEIGHT = 600
SCREEN_SIZE = (WIDTH, HEIGHT)
TEXT_FIELD_HEIGHT = 50
BACKGROUND_HEIGHT = HEIGHT - TEXT_FIELD_HEIGHT
TEXT_PADDING = 8
TEXT_COORDINATES = (TEXT_PADDING, BACKGROUND_HEIGHT + TEXT_PADDING)

# COLORS
BACKGROUND_COLOR = THECOLORS['yellow']
OPTIONS_TEXT_BACKGROUND_COLOR = (71, 26, 6)
OPTIONS_TEXT_COLOR = THECOLORS['white']
TEXT_BACKGROUND_COLOR = THECOLORS['green']
TEXT_COLOR = THECOLORS['black']
WALL_COLOR = THECOLORS['brown']
RUNNER_COLOR = THECOLORS['red']
SOLUTION_COLOR = THECOLORS['red']

# TEXT
FONT = pygame.font.SysFont('couriernew', 34)
OPTIONS_TEXT_SIZE = 40
OPTIONS_FONT = pygame.font.SysFont('couriernew', OPTIONS_TEXT_SIZE, bold=True)

# MAZE OPTIONS
DEFAULT_GENERATOR = 'kruskal-generator'
SMALL = (5, 8)
MEDIUM = (8, 12)
BIG = (15, 20)
